CREATE TABLE Paper (
    ID COUNTER PRIMARY KEY,
    WoSID VARCHAR,
    DOI VARCHAR,
    Title Memo,
    [Year] int,
    [Index] int,
    Addresses Memo,
    AuthorNames Memo,
    AuthorCount int,
    Author1 VARCHAR,
    Author2 VARCHAR,
    Author3 VARCHAR,
    Author4 VARCHAR,
    Author5 VARCHAR,
    Author6 VARCHAR,
    Author7 VARCHAR,
    Author8 VARCHAR,
    Author9 VARCHAR
);